import { type Question } from '@/lib/types';

export const questions: Question[] = [
  {
    id: 'comfortable',
    type: 'multiple-choice',
    text: 'How comfortable are you around me?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'heard',
    type: 'multiple-choice',
    text: 'Do I make you feel heard?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'advice',
    type: 'multiple-choice',
    text: 'How good am I at giving advice?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'trust',
    type: 'multiple-choice',
    text: 'Do I seem like someone you can trust?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'approachable',
    type: 'multiple-choice',
    text: 'How approachable do I seem?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'teammate',
    type: 'multiple-choice',
    text: 'Am I a good teammate?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'disagreements',
    type: 'multiple-choice',
    text: 'Do I handle disagreements well?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'pressure',
    type: 'multiple-choice',
    text: 'How well do I handle pressure in social situations?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'humor',
    type: 'multiple-choice',
    text: 'How would you describe my sense of humor?',
    options: ['Excellent', 'Good', 'Average', 'Bad', 'Terrible'],
  },
  {
    id: 'optimistic',
    type: 'sliding-bar',
    text: 'On a scale of 1 to 10, how optimistic do I seem?',
  },
  {
    id: 'open_minded',
    type: 'multiple-choice',
    text: 'How open-minded do you think I am?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'listening',
    type: 'multiple-choice',
    text: 'How good am I at listening?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'genuine',
    type: 'multiple-choice',
    text: 'Do I come across as genuine?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'ambitious',
    type: 'multiple-choice',
    text: 'How ambitious do I seem to be?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'influence',
    type: 'multiple-choice',
    text: 'Am I a good influence?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'reliable',
    type: 'multiple-choice',
    text: 'How reliable do you think I am?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'sensitive',
    type: 'multiple-choice',
    text: 'How sensitive do I seem?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'supportive',
    type: 'multiple-choice',
    text: 'Am I a supportive person?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'creativity',
    type: 'sliding-bar',
    text: 'Rate my creativity.',
  },
  {
    id: 'arrogant',
    type: 'multiple-choice',
    text: 'How arrogant I am.',
    options: ['Not at all', 'A little', 'Moderately', 'Very', 'Extremely'],
  },
  {
    id: 'friendliness',
    type: 'sliding-bar',
    text: 'Rate my friendliness.',
  },
  {
    id: 'looks',
    type: 'multiple-choice',
    text: 'How handsome/beautiful I look.',
    options: [
      'Stunning',
      'Very attractive',
      'Attractive',
      'Average',
      'Not my type',
    ],
  },
  {
    id: 'attractive',
    type: 'multiple-choice',
    text: 'Am I attractive?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'cute',
    type: 'multiple-choice',
    text: 'Do I look cute?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'articulate',
    type: 'multiple-choice',
    text: 'How articulate am I when I speak?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'organized',
    type: 'multiple-choice',
    text: 'How organized do I seem?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'passionate',
    type: 'multiple-choice',
    text: 'How passionate do I seem about my interests?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'determined',
    type: 'multiple-choice',
    text: 'How determined do I appear to be?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'resourceful',
    type: 'multiple-choice',
    text: 'How resourceful do I seem?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'judgmental',
    type: 'multiple-choice',
    text: 'How judgmental do I sometimes come across?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'intense',
    type: 'multiple-choice',
    text: 'Am I ever too intense?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'talk_too_much',
    type: 'multiple-choice',
    text: 'Do I talk about myself too much?',
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
  {
    id: 'admit_wrong',
    type: 'multiple-choice',
    text: "How good am I at admitting when I'm wrong?",
    options: ['Yes', 'Probably', 'Idk', 'Probably not', 'No'],
  },
];
